# Generated by Django 5.1.13 on 2025-10-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0093_remove_friendlist_friend_remove_friendlist_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('iso_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='country',
            new_name='country_old',
        ),
    ]
