# Generated by Django 5.1.13 on 2025-10-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0095_beer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='country_old',
        ),
    ]
