# Generated by Django 5.1.13 on 2025-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0097_beer_is_christmas_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='is_christmas_release',
            field=models.BooleanField(default=False),
        ),
    ]
