# Generated by Django 5.1.13 on 2025-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0098_release_is_christmas_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='price_per_alcohol_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
