# Generated by Django 5.2.9 on 2026-01-31 12:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('beers', '0102_alter_tasted_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithTasted',
            fields=[
            ],
            options={
                'verbose_name': 'User Tasted',
                'verbose_name_plural': 'User Tasteds',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
