# Generated by Django 5.2.9 on 2026-02-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0104_userwithlists_userlist_userlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlistitem',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.RenameField(
            model_name='userlistitem',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userlistitem',
            old_name='position',
            new_name='sort_order',
        ),
        migrations.AddField(
            model_name='userlist',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='list_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('shopping', 'Shopping'), ('cellar', 'Cellar'), ('event', 'Event')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='userlist',
            name='selected_store_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlistitem',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userlistitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userlistitem',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
