# Generated by Django 5.2.11 on 2026-02-27 07:11

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('beers', '0106_untappdcheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntappdRssFeed',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='untappd_rss_feed', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('feed_url', models.URLField(max_length=500)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWithCheckins',
            fields=[
            ],
            options={
                'verbose_name': 'User Checkin',
                'verbose_name_plural': 'User Checkins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
