# Generated by Django 5.2.11 on 2026-02-27 08:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0107_untappdrssfeed_userwithcheckins"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasted",
            name="rating",
        ),
        migrations.DeleteModel(
            name="UntappdCheckin",
        ),
        migrations.CreateModel(
            name="UntappdCheckin",
            fields=[
                (
                    "untpd_checkin_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("untpd_beer_id", models.IntegerField()),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("checkin_at", models.DateTimeField(blank=True, null=True)),
                ("synced", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="untappd_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["synced", "untpd_beer_id"],
                        name="beers_untap_synced_e445b7_idx",
                    ),
                    models.Index(
                        fields=["user", "untpd_beer_id"],
                        name="beers_untap_user_id_ce7cac_idx",
                    ),
                ],
            },
        ),
    ]
