# Generated by Django 5.2.13 on 2026-04-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0108_multi_checkin_and_remove_tasted_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntappdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untappd_list_id', models.IntegerField(unique=True)),
                ('untappd_username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('item_count', models.IntegerField(default=0)),
                ('untappd_beer_ids', models.JSONField(default=list)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='badge',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_set', to='beers.beer'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_set', to='beers.beer'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='list_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('shopping', 'Shopping'), ('cellar', 'Cellar'), ('event', 'Event'), ('untappd', 'Untappd')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='userlist',
            name='untappd_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_lists', to='beers.untappdlist'),
        ),
    ]
