# Generated by Django 5.2.13 on 2026-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0109_untappd_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
