# Generated by Django 5.2.13 on 2026-04-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0111_untappd_list_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='value_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
