# Generated by Django 5.2.13 on 2026-04-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0113_backfill_value_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='untappdlist',
            name='sync_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
