# Generated by Django 5.2.15 on 2026-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0119_vmpcrawlstate_stock_last_seen_in_stock_sync_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="vmp_brewery",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
