# Generated by Django 5.2.15 on 2026-07-21 21:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0120_beer_vmp_brewery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brewery",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("slug", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "label_url",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("untpd_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Breweries",
            },
        ),
        migrations.RemoveField(
            model_name="beer",
            name="brewery",
        ),
        migrations.AddField(
            model_name="beer",
            name="brewery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beers",
                to="beers.brewery",
            ),
        ),
    ]
