# Generated by Django 6.1 on 2026-09-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0122_clean_brewery'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='package_type',
            field=models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('can', 'Can'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
