# Generated by Django 5.1.13 on 2025-10-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0092_alter_externalapi_baseurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tasted',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='tasted',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='Tasted',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
