# Generated by Django 5.1.13 on 2025-10-25 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0094_country_rename_country_beer_country_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers', to='beers.country'),
        ),
    ]
