# Generated by Django 5.1.13 on 2025-10-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0096_remove_beer_country_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_christmas_beer',
            field=models.BooleanField(default=False),
        ),
    ]
