# Generated by Django 5.2.9 on 2026-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0100_tasted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasted',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
