# Generated by Django 5.2.9 on 2026-01-30 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0101_tasted_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasted',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
