# Generated by Django 5.2.13 on 2026-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0110_option_value_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='untappdlist',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='untappdlist',
            name='untappd_list_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='untappdlist',
            constraint=models.UniqueConstraint(fields=('untappd_username', 'untappd_list_id'), name='unique_untappd_list'),
        ),
    ]
