# Generated by Django 5.2.13 on 2026-04-21 08:39

from django.db import migrations


def backfill_value_score(apps, schema_editor):
    Beer = apps.get_model("beers", "Beer")
    beers_to_update = []
    for beer in Beer.objects.filter(
        rating__isnull=False, rating__gt=0,
        price_per_volume__isnull=False, price_per_volume__gt=0,
    ).iterator(chunk_size=2000):
        beer.value_score = (
            (beer.rating**4.8) / ((beer.price_per_volume / 100) ** 0.32)
        ) * 0.0176
        beers_to_update.append(beer)
        if len(beers_to_update) >= 2000:
            Beer.objects.bulk_update(beers_to_update, ["value_score"])
            beers_to_update = []
    if beers_to_update:
        Beer.objects.bulk_update(beers_to_update, ["value_score"])


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0112_beer_value_score_field'),
    ]

    operations = [
        migrations.RunPython(backfill_value_score, migrations.RunPython.noop),
    ]
