# Generated by Django 5.2.13 on 2026-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0116_userlist_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='show_notes',
            field=models.BooleanField(default=True),
        ),
    ]
