# Generated by Django 5.2.14 on 2026-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0118_followed_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmpCrawlState',
            fields=[
                ('scope', models.CharField(default='catalog', max_length=50, primary_key=True, serialize=False)),
                ('category', models.IntegerField(default=0)),
                ('page', models.IntegerField(default=0)),
                ('started', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='last_seen_in_stock_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='stock_sync_category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='stock_sync_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='stock_sync_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
